### ISSUE TITLE
How to get basic auth username / password?

### ISSUE THREAD

**Issue by pcj** [cloudposse/terraform-aws-ecr#23]
Apologies in advance for this possibly naive question, but...

We have existing code that wants to push to an azure container registry via basic auth username / password.  To use ecr, looking to replicate the same thing here.  

The `$ aws ecr get-login` command returns `-u AWS` and `-p {STS_TOKEN_REALLY_LONG_STRING_HERE}`.  

Is it possible to fetch this information via the outputs of this terraform module?  If not, what is the recommended approach to that? (getting the STS token)

**Comment by aknysh** [comment]
@pcj 
One approach, in the app repo itself, add `buildspec.yml` file, in which you specify the commands you want to execute during the build.
For example, we have this repo https://github.com/cloudposse/terraform-aws-jenkins, which includes ECR and CodePipeline/CodeBuild. CodeBuild builds this repo https://github.com/cloudposse/jenkins and then pushes the image to ECR. The repo has `buildspec.yml` file with all the commands to login to ECR, build Docker image, and push it to ECR
https://github.com/cloudposse/jenkins/blob/master/buildspec.yml

**Comment by aknysh** [comment]
Terraform does not have the ability to get the ECR login
https://www.terraform.io/docs/providers/aws/r/ecr_repository.html
Although you can run any command using https://www.terraform.io/docs/provisioners/local-exec.html

**Comment by pcj** [comment]
OK thanks @aknysh.  Seems like a missing spot in the terraform coverage, no?  (not to be able to fetch the token).  I'll go ahead and close this issue.  Thanks!
