### ISSUE TITLE
resource_full_access iam document is missing a few permissions

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-ecr#44]
## Describe the Bug

If the data source `resource_full_access` is truly for full access, then https://github.com/cloudposse/terraform-aws-ecr/blob/master/main.tf#L116 is missing the following permissions

```
"ecr:SetRepositoryPolicy",
"ecr:DeleteRepositoryPolicy",
"ecr:DeleteRepository",
"ecr:BatchDeleteImage",
```

## Expected Behavior
Have those permissions above

## Additional Context

There are a few ways we can solve this and my preference is the first.

* Add the above perms to the `resource_full_access` document
* Create a variable to override all those permissions or append those perms
* Give `resource_full_access` all the ecr perms using `ecr:*`

@maximmi @aknysh

**Comment by maximmi** [comment]
fixed in #45
