### ISSUE TITLE
0.15 -> 0.16 transition wants to destroy and recreate all repos

### ISSUE THREAD

**Issue by mark-at-nuna** [cloudposse/terraform-aws-ecr#58]
## Describe the Bug
When I update my configuration to use tagged version 0.16.0, from 0.15.0, terraform tries to destroy my repositories and create new ones in their places. It looks like the internal resource naming has changed. Do I need to run `terraform state mv` for all of my repos? I have a lot of repos.

## Expected Behavior
If the new module is going to change the repositories, I expect them to be modified in place. Destroying them will delete my entire ECS infrastructure.

## Steps to Reproduce
1. Create a repository using Terraform and module source `git::https://github.com/cloudposse/terraform-aws-ecr.git?ref=tags/0.15.0`
2. Modify the configuration to use version 0.16.0 (or any later version up to 0.20.0), so `git diff` might output e.g.
```
 module "ecr_dev" {
-  source          = "git::https://github.com/cloudposse/terraform-aws-ecr.git?ref=tags/0.15.0"
+  source          = "git::https://github.com/cloudposse/terraform-aws-ecr.git?ref=tags/0.16.0"
   name            = "my-repo"
```
3. Run `terraform plan`

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

```
module.ecr_dev.aws_ecr_repository.default[0] will be destroyed
module.ecr_dev.aws_ecr_repository.name["my-repo"] will be created
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
terraform 0.12.25 on OS X.

**Comment by nitrocode** [comment]
Unsure if that was an intended change. You'll have to do a `terraform state mv` to get around it

```
terraform state mv \
  'module.ecr_dev.aws_ecr_repository.default[0]' \
  'module.ecr_dev.aws_ecr_repository.name["my-repo"]'
```
